version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: itzkeshav/backend:latest
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: itzkeshav/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: